apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  steps:
    - name: remove-temp-files
      image: alpine
      script: |
        #!/bin/sh
        echo "Cleaning workspace..."
        rm -rf /workspace/*

---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-nose-tests
spec:
  steps:
    - name: nose-test
      image: python:3.9
      script: |
        #!/bin/bash
        pip install nose
        nosetests
